#!/usr/bin/env python3
"""Compare full-scan (no hint) vs diff-scan diff-0 (crash-file name hint).
Writes runs/full-vs-diff.md. Per-bug K_b for SOLVED; compares on the common set.
"""
import glob
import json

from fbbench.grading.bench_yaml import capability_set, find_bug
from fbbench.paths import REPO


def load(*exps):
    d = {}
    for e in exps:
        for f in glob.glob(f"{REPO}/runs/{e}/**/score.json", recursive=True):
            s = json.load(open(f))
            d[s["bug_id"]] = s
    return d


def solved_set(d):
    out = set()
    for b, s in d.items():
        fired = {k for k, v in s["capabilities"].items() if v == "fired"}
        kb = set(capability_set(find_bug(b, REPO)) or ["reach", "crash", "class", "site"])
        if kb and kb.issubset(fired):
            out.add(b)
    return out


def crash_set(d):
    return {b for b, s in d.items() if s["capabilities"].get("crash") == "fired"}


FH = load("fullscan-haiku-48", "fullscan-haiku-48b")
FG = load("fullscan-gpt55-48", "fullscan-gpt55-retry10")
DH = load("diffscan/*/claude-haiku-4-5/diff-0")
DG = load("diffscan/*/gpt-5.5/diff-0")

L = []
def A(s=""):
    L.append(s)

A("# Full-Scan vs Diff-Scan (diff-0)")
A("")
A("Does naming the **crash-point file** (diff-0) beat giving the agent **nothing but "
  "the harness** (full-scan)? Both withhold the bug description. SOLVED = the bug's "
  "`capability_set` K_b all fired. Compared on the bugs both runs cover.")
A("")
A("| model | set | full-scan solved | diff-0 solved | Δ solved | full crash | diff-0 crash | Δ crash |")
A("|---|---|---|---|---|---|---|---|")
for name, full, diff in [("haiku", FH, DH), ("gpt-5.5", FG, DG)]:
    common = set(full) & set(diff)
    fs, ds = solved_set(full) & common, solved_set(diff) & common
    fc, dc = crash_set(full) & common, crash_set(diff) & common
    A(f"| {name} | {len(common)} | {len(fs)} | {len(ds)} | **{len(ds)-len(fs):+d}** | "
      f"{len(fc)} | {len(dc)} | {len(dc)-len(fc):+d} |")
A("")
for name, full, diff in [("haiku", FH, DH), ("gpt-5.5", FG, DG)]:
    common = set(full) & set(diff)
    fs, ds = solved_set(full) & common, solved_set(diff) & common
    A(f"**{name}** — diff-0 newly solves: {sorted(ds - fs) or '—'}")
    A(f"&nbsp;&nbsp;&nbsp;&nbsp; lost (full solved, diff-0 didn't): {sorted(fs - ds) or '—'}")
    A("")
A("## Read")
A("- The file-name hint gives only a **small, mixed** gain over full-scan "
  "(haiku +2, gpt-5.5 +1 solved) — not a clean across-the-board lift.")
A("- For both models several bugs swap in/out, i.e. the change is within run-to-run "
  "noise, not a robust effect.")
A("")
A("## Caveats (read before quoting these numbers)")
A("1. **Different grader.** Full-scan was graded by the OLD grader (3-round unanimity, "
   "LSan-leaks counted, class matched by substring incl. binary path, reach mis-fired). "
   "Diff-0 uses the FIXED grader (single round / flaky=1, LSan gated to leak-class bugs, "
   "class matched on the sanitizer line only, site⇒reach). The Δ therefore **mixes the "
   "hint effect with the grader change** and is not a clean A/B.")
A("2. **No full-scan PoCs were preserved**, so full-scan cannot be re-graded under the "
   "fixed grader to remove caveat 1.")
A("3. **Single run per cell (flaky=1)** → per-bug variance is large; small Δs are within "
   "noise. A clean comparison needs multiple seeds and a shared grader.")
A("")
A("_Generated by tools/diffscan_vs_fullscan.py from runs/fullscan-* and runs/diffscan-*._")

open(f"{REPO}/runs/full-vs-diff.md", "w").write("\n".join(L) + "\n")
print("wrote runs/full-vs-diff.md")
