#!/usr/bin/env python3
"""Freeze the diff-scan file-name hints into each bug bundle (one-time).

The diff-scan tier hands the agent the NAME(s) of the file(s) a PR "touched":

    diff-0 : just the crash-relevant file(s)
    diff-1 : crash file(s) + 1 fuzzer-relevant distractor name
    diff-2 : crash file(s) + 2 distractors
    diff-3 : crash file(s) + 3 distractors

Live, that list comes from `diffscan_lib._live_file_list`, which fetches the
repo's source tree from GitHub at run time and draws distractors with a seeded
RNG. Even though the draw is seeded, the *pool* depends on the fetched tree, so
the result can drift if the tree fetch changes, and every run pays a network
round-trip. This script runs that live logic ONCE and writes the result to
`<bug>/diffscan.yaml` (repo-relative paths, frozen order). After that,
`file_list()` reads the frozen file and never recomputes — so a given
(bug, level) is byte-stable across runs, models, and time.

`diffscan.yaml` is NOT in mcp_client.SANDBOX_ENTRIES, so it is never staged into
the agent's view — the crash_files it records stay oracle-side.

Usage:
    PYTHONPATH=.:tools python tools/diffscan_freeze.py            # all bugs
    PYTHONPATH=.:tools python tools/diffscan_freeze.py --bug netsnmp-...   # one
    PYTHONPATH=.:tools python tools/diffscan_freeze.py --check    # verify, no write
"""
from __future__ import annotations

import argparse
import os
import sys

import yaml

from fbbench.paths import REPO

import diffscan_lib as dl

LEVELS = (0, 1, 2, 3)

_HEADER = (
    "# Frozen diff-scan PR file-name hints — paths are repo-relative to the\n"
    "# upstream source tree at the bug's vuln_commit. Generated by\n"
    "# tools/diffscan_freeze.py from the live tree+distractor logic; regenerate\n"
    "# with that script rather than hand-editing. Read by diffscan_lib.file_list.\n"
)


def _iter_bug_dirs(one: str | None):
    bugs_root = REPO / "bugs"
    for proj in sorted(os.listdir(bugs_root)):
        proj_dir = bugs_root / proj
        if not proj_dir.is_dir():
            continue
        for name in sorted(os.listdir(proj_dir)):
            d = proj_dir / name
            if not (d / "bench.yaml").is_file():
                continue
            if one and name != one:
                continue
            yield str(d)


def _compute(bug_dir: str) -> dict | None:
    """Run the LIVE logic for every level; return the frozen-file payload, or
    None if the bug has no crash file (site-less OOM/leak — diff-scan N/A)."""
    meta = dl.bug_meta(bug_dir)
    if not meta["crash_files"]:
        return None
    levels: dict[str, dict] = {}
    crash: list[str] = []
    for lv in LEVELS:
        try:
            fl = dl._live_file_list(meta, lv)
        except NotImplementedError:
            # Non-GitHub host: diff-0 still resolves, higher levels need the tree.
            continue
        crash = fl["crash"]  # identical across levels; last write wins
        levels[str(lv)] = {"files": fl["files"], "distractors": fl["distractors"]}
    if not levels:
        return None
    return {
        "repo": meta["repo"],
        "commit": meta["commit"],
        "crash_files": list(crash),
        "levels": levels,
    }


def _dump(payload: dict) -> str:
    return _HEADER + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)


def main() -> int:
    ap = argparse.ArgumentParser(description="Freeze diff-scan file lists per bug")
    ap.add_argument("--bug", help="only this bug (basename)")
    ap.add_argument("--check", action="store_true",
                    help="recompute and diff against the committed file; write nothing")
    args = ap.parse_args()

    wrote = skipped = unchanged = drift = 0
    for bug_dir in _iter_bug_dirs(args.bug):
        bug = os.path.basename(bug_dir)
        payload = _compute(bug_dir)
        if payload is None:
            skipped += 1
            print(f"SKIP  {bug}  (no crash file / no fetchable tree)")
            continue
        out = os.path.join(bug_dir, dl.FROZEN_NAME)
        text = _dump(payload)
        if args.check:
            old = open(out).read() if os.path.exists(out) else ""
            if old == text:
                unchanged += 1
            else:
                drift += 1
                print(f"DRIFT {bug}  (committed != recomputed)")
            continue
        old = open(out).read() if os.path.exists(out) else None
        if old == text:
            unchanged += 1
            continue
        with open(out, "w") as fp:
            fp.write(text)
        wrote += 1
        nlv = len(payload["levels"])
        print(f"WROTE {bug}  ({nlv} level(s))")

    if args.check:
        print(f"\ncheck: {unchanged} unchanged, {drift} drift, {skipped} skipped")
        return 1 if drift else 0
    print(f"\nfroze: {wrote} written, {unchanged} unchanged, {skipped} skipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
