#!/usr/bin/env python3
"""Generate per-bug vuln.yaml — HIDDEN ground-truth metadata.

vuln.yaml records the vulnerability classification + analysis metadata that
must NOT reach the agent (category == the T2 class answer). It is deliberately
kept OUT of mcp_client.SANDBOX_ENTRIES, so the allowlist staging never copies it
into the agent's view (fail-safe: hidden by default).

Mechanically-derivable fields are filled from the existing single sources of
truth (grader/expected.yaml, bench.yaml); `difficulty` and a few CWEs are left
for the human passes (issues #11 / #12). Re-run any time; only changed files are
rewritten.

Usage:
    PYTHONPATH=.:tools python tools/gen_vuln_yaml.py            # all bugs
    PYTHONPATH=.:tools python tools/gen_vuln_yaml.py --check    # diff only
"""
from __future__ import annotations

import argparse
import os
import sys

import yaml

from fbbench.paths import REPO

# Bugs to park via active:false. Empty for now — the whole corpus ships active;
# the `active` switch + run/grade/sweep filtering is wired up and ready, so any
# bug can be parked later by adding it here (or editing its vuln.yaml). The
# cross-repo third-party-lib bugs (jsoncpp/graal/skia) are the likely first
# candidates once their modelling is settled — see issue #14.
DEACTIVATED: set[str] = set()

# Crash/sanitizer class -> normalized semantic category. Coarse first pass;
# refine per-bug under #12. (No CWE: never recorded upstream and too ambiguous
# — one bug often maps to several.)
_CLASS_MAP = {
    "heap-buffer-overflow":   "heap-buffer-overflow",
    "heap-use-after-free":    "use-after-free",
    "use-after-free":         "use-after-free",
    "stack-buffer-overflow":  "stack-buffer-overflow",
    "stack-buffer-underflow": "stack-buffer-underflow",
    "stack-overflow":         "stack-exhaustion",
    "oob-read":               "out-of-bounds-read",
    "out-of-bounds-access":   "out-of-bounds-access",
    "segv":                   "null-pointer-dereference",
    "null-pointer-dereference": "null-pointer-dereference",
    "memory-leak":            "memory-leak",
    "oom":                    "uncontrolled-resource-consumption",
    "allocation-size-too-big": "excessive-allocation",
    "timeout":                "excessive-iteration",
    "undefined-behavior":     "undefined-behavior",
    "misaligned-access":      "misaligned-access",
    "uncaught-exception":     "uncaught-exception",
    "class-cast":             "type-confusion",
    "abrt":                   "reachable-assertion",
    "abort":                  "reachable-assertion",
}

_HEADER = (
    "# vuln.yaml — HIDDEN ground-truth metadata. NOT in SANDBOX_ENTRIES, so it is\n"
    "# never staged into the agent's view. `category` is the T2 class answer — do\n"
    "# not move it into an agent-visible file. Generated by tools/gen_vuln_yaml.py;\n"
    "# `sanitizer`/`disclosed`/`vuln_version` mirror their source-of-truth in\n"
    "# grader/expected.yaml + bench.yaml (regenerate rather than hand-editing those).\n"
    "# `difficulty` and `category` refinement are the human passes (#11 / #12).\n"
)


def _iter_bug_dirs(one: str | None):
    for proj in sorted(os.listdir(REPO / "bugs")):
        proj_dir = REPO / "bugs" / proj
        if not proj_dir.is_dir():
            continue
        for name in sorted(os.listdir(proj_dir)):
            d = proj_dir / name
            if (d / "bench.yaml").is_file() and (not one or name == one):
                yield str(d)


def _compute(bug_dir: str) -> dict:
    bug = os.path.basename(bug_dir)
    bench = yaml.safe_load(open(os.path.join(bug_dir, "bench.yaml"))) or {}
    tgt = bench.get("target", {}) or {}
    exp = {}
    exp_path = os.path.join(bug_dir, "grader", "expected.yaml")
    if os.path.exists(exp_path):
        exp = yaml.safe_load(open(exp_path)) or {}
    cls = (exp.get("class") or {})
    raw = cls.get("expected") or ""
    sem = _CLASS_MAP.get(raw, raw or None)
    return {
        "category": sem,
        "difficulty": "none",
        "metadata": {
            "sanitizer": cls.get("sanitizer") or None,
            "disclosed": bench.get("disclosed"),
            "vuln_version": tgt.get("vuln_commit") or None,
        },
        "active": bug not in DEACTIVATED,
    }


def _dump(payload: dict) -> str:
    return _HEADER + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate per-bug vuln.yaml")
    ap.add_argument("--bug")
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = ap.parse_args()

    wrote = unchanged = drift = 0
    for bug_dir in _iter_bug_dirs(args.bug):
        bug = os.path.basename(bug_dir)
        text = _dump(_compute(bug_dir))
        out = os.path.join(bug_dir, "vuln.yaml")
        old = open(out).read() if os.path.exists(out) else None
        if old == text:
            unchanged += 1
            continue
        if args.check:
            drift += 1
            print(f"DRIFT {bug}")
            continue
        with open(out, "w") as fp:
            fp.write(text)
        wrote += 1
        print(f"WROTE {bug}  ({'INACTIVE' if bug in DEACTIVATED else 'active'})")

    if args.check:
        print(f"\ncheck: {unchanged} unchanged, {drift} drift")
        return 1 if drift else 0
    print(f"\nvuln.yaml: {wrote} written, {unchanged} unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
