#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
LIB="${DIR}/../lib"
exec java -Xmx256m \
    -cp "${LIB}/classes:${LIB}/fontbox.jar:${LIB}/deps/*" \
    -DtargetClass=CMapFuzzer \
    PocRunner "$@"
